export const TURKEY_CITIES: Record<string, string[]> = {
  "Adana": ["Seyhan", "Yüreğir", "Çukurova", "Sarıçam", "Ceyhan", "Kozan", "İmamoğlu", "Karataş", "Karaisalı", "Pozantı", "Feke", "Aladağ", "Saimbeyli", "Tufanbeyli", "Yumurtalık"],
  "Adıyaman": ["Merkez", "Kahta", "Besni", "Gölbaşı", "Gerger", "Sincik", "Tut", "Çelikhan", "Samsat"],
  "Afyonkarahisar": ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Sinanpaşa", "Emirdağ", "Şuhut", "Çay", "İhsaniye", "İscehisar", "Sultandağı", "Başmakçı", "Dazkırı", "Çobanlar", "Evciler", "Hocalar", "Kızılören"],
  "Ağrı": ["Merkez", "Doğubayazıt", "Patnos", "Diyadin", "Eleşkirt", "Tutak", "Taşlıçay", "Hamur"],
  "Amasya": ["Merkez", "Merzifon", "Suluova", "Taşova", "Göynücek", "Gümüşhacıköy", "Hamamözü"],
  "Ankara": ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Altındağ", "Pursaklar", "Gölbaşı", "Polatlı", "Çubuk", "Kahramankazan", "Beypazarı", "Elmadağ", "Nallıhan", "Haymana", "Kızılcahamam", "Akyurt", "Ayaş", "Bala", "Kalecik", "Güdül", "Çamlıdere", "Evren"],
  "Antalya": ["Muratpaşa", "Kepez", "Konyaaltı", "Alanya", "Manavgat", "Serik", "Aksu", "Kumluca", "Kaş", "Korkuteli", "Gazipaşa", "Finike", "Kemer", "Elmalı", "Demre", "Akseki", "Gündoğmuş", "İbradı"],
  "Artvin": ["Merkez", "Hopa", "Borçka", "Arhavi", "Şavşat", "Yusufeli", "Ardanuç", "Murgul", "Kemalpaşa"],
  "Aydın": ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "İncirliova", "Çine", "Germencik", "Karacasu", "Köşk", "Sultanhisar", "Bozdoğan", "Yenipazar", "Buharkent", "Karpuzlu", "Koçarlı"],
  "Balıkesir": ["Karesi", "Altıeylül", "Bandırma", "Edremit", "Gönen", "Ayvalık", "Burhaniye", "Bigadiç", "Dursunbey", "Susurluk", "Erdek", "Sındırgı", "İvrindi", "Havran", "Kepsut", "Manyas", "Savaştepe", "Gömeç", "Balya", "Marmara"],
  "Bilecik": ["Merkez", "Bozüyük", "Osmaneli", "Söğüt", "Gölpazarı", "Pazaryeri", "İnhisar", "Yenipazar"],
  "Bingöl": ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı", "Kiğı", "Yedisu", "Yayladere"],
  "Bitlis": ["Merkez", "Tatvan", "Güroymak", "Ahlat", "Hizan", "Mutki", "Adilcevaz"],
  "Bolu": ["Merkez", "Gerede", "Mudurnu", "Mengen", "Göynük", "Yeniçağa", "Dörtdivan", "Seben", "Kıbrıscık"],
  "Burdur": ["Merkez", "Bucak", "Gölhisar", "Yeşilova", "Çavdır", "Tefenni", "Ağlasun", "Karamanlı", "Altınyayla", "Kemer", "Çeltikçi"],
  "Bursa": ["Osmangazi", "Yıldırım", "Nilüfer", "İnegöl", "Gemlik", "Mustafakemalpaşa", "Mudanya", "Gürsu", "Kestel", "Karacabey", "Orhangazi", "Yenişehir", "İznik", "Orhaneli", "Keles", "Büyükorhan", "Harmancık"],
  "Çanakkale": ["Merkez", "Biga", "Çan", "Gelibolu", "Yenice", "Ayvacık", "Ezine", "Bayramiç", "Lapseki", "Eceabat", "Gökçeada", "Bozcaada"],
  "Çankırı": ["Merkez", "Çerkeş", "Ilgaz", "Orta", "Şabanözü", "Kurşunlu", "Yapraklı", "Kızılırmak", "Eldivan", "Atkaracalar", "Korgun", "Bayramören"],
  "Çorum": ["Merkez", "Sungurlu", "Osmancık", "İskilip", "Alaca", "Bayat", "Kargı", "Mecitözü", "Ortaköy", "Uğurludağ", "Dodurga", "Oğuzlar", "Laçin", "Boğazkale"],
  "Denizli": ["Pamukkale", "Merkezefendi", "Çivril", "Acıpayam", "Tavas", "Honaz", "Sarayköy", "Buldan", "Kale", "Çal", "Çameli", "Serinhisar", "Bozkurt", "Güney", "Çardak", "Bekilli", "Beyağaç", "Babadağ", "Baklan"],
  "Diyarbakır": ["Bağlar", "Kayapınar", "Yenişehir", "Sur", "Ergani", "Bismil", "Silvan", "Çermik", "Çınar", "Dicle", "Kulp", "Hani", "Eğil", "Hazro", "Lice", "Kocaköy", "Çüngüş"],
  "Edirne": ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa", "Meriç", "Lalapaşa", "Süloğlu", "Enez"],
  "Elazığ": ["Merkez", "Kovancılar", "Karakoçan", "Palu", "Arıcak", "Baskil", "Maden", "Sivrice", "Keban", "Alacakaya", "Ağın"],
  "Erzincan": ["Merkez", "Tercan", "Üzümlü", "Çayırlı", "İliç", "Kemaliye", "Refahiye", "Otlukbeli", "Kemah"],
  "Erzurum": ["Yakutiye", "Palandöken", "Aziziye", "Horasan", "Oltu", "Pasinler", "Karayazı", "Hınıs", "Tekman", "Karaçoban", "Aşkale", "Şenkaya", "Çat", "Tortum", "Uzundere", "Olur", "Narman", "İspir", "Pazaryolu", "Köprüköy"],
  "Eskişehir": ["Odunpazarı", "Tepebaşı", "Sivrihisar", "Çifteler", "Seyitgazi", "Alpu", "Mihalıççık", "Mahmudiye", "Beylikova", "İnönü", "Sarıcakaya", "Günyüzü", "Mihalgazi", "Han"],
  "Gaziantep": ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Araban", "Oğuzeli", "Yavuzeli", "Karkamış"],
  "Giresun": ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu", "Şebinkarahisar", "Keşap", "Dereli", "Yağlıdere", "Piraziz", "Eynesil", "Alucra", "Çanakçı", "Doğankent", "Güce", "Çamoluk"],
  "Gümüşhane": ["Merkez", "Kelkit", "Şiran", "Torul", "Köse", "Kürtün"],
  "Hakkari": ["Merkez", "Yüksekova", "Şemdinli", "Çukurca", "Derecik"],
  "Hatay": ["Antakya", "İskenderun", "Defne", "Dörtyol", "Samandağ", "Kırıkhan", "Reyhanlı", "Arsuz", "Payas", "Altınözü", "Hassa", "Erzin", "Yayladağı", "Kumlu", "Belen"],
  "Isparta": ["Merkez", "Yalvaç", "Eğirdir", "Şarkikaraağaç", "Gelendost", "Keçiborlu", "Senirkent", "Sütçüler", "Gönen", "Uluborlu", "Atabey", "Aksu", "Yenişarbademli"],
  "Mersin": ["Tarsus", "Toroslar", "Akdeniz", "Yenişehir", "Mezitli", "Erdemli", "Silifke", "Anamur", "Mut", "Gülnar", "Bozyazı", "Çamlıyayla", "Aydıncık"],
  "İstanbul": ["Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu"],
  "İzmir": ["Aliağa", "Balçova", "Bayındır", "Bayraklı", "Bergama", "Beydağ", "Bornova", "Buca", "Çeşme", "Çiğli", "Dikili", "Foça", "Gaziemir", "Güzelbahçe", "Karabağlar", "Karaburun", "Karşıyaka", "Kemalpaşa", "Kınık", "Kiraz", "Konak", "Menderes", "Menemen", "Narlıdere", "Ödemiş", "Seferihisar", "Selçuk", "Tire", "Torbalı", "Urla"],
  "Kars": ["Merkez", "Kağızman", "Sarıkamış", "Selim", "Digor", "Arpaçay", "Akyaka", "Susuz"],
  "Kastamonu": ["Merkez", "Tosya", "Taşköprü", "Cide", "İnebolu", "Araç", "Devrekani", "Daday", "Bozkurt", "Abana", "Azdavay", "Çatalzeytin", "Küre", "İhsangazi", "Pınarbaşı", "Şenpazar", "Seydiler", "Hanönü", "Doğanyurt", "Ağlı"],
  "Kayseri": ["Melikgazi", "Kocasinan", "Talas", "Develi", "Yahyalı", "Bünyan", "Pınarbaşı", "Tomarza", "Yeşilhisar", "Sarıoğlan", "Hacılar", "Sarız", "Felahiye", "Özvatan", "Akkışla", "İncesu"],
  "Kırklareli": ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar", "Demirköy", "Pehlivanköy", "Kofçaz"],
  "Kırşehir": ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar", "Boztepe", "Akçakent"],
  "Kocaeli": ["İzmit", "Gebze", "Darıca", "Gölcük", "Körfez", "Derince", "Çayırova", "Kartepe", "Başiskele", "Karamürsel", "Kandıra", "Dilovası"],
  "Konya": ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Çumra", "Seydişehir", "Ilgın", "Cihanbeyli", "Kulu", "Karapınar", "Kadınhanı", "Sarayönü", "Bozkır", "Doğanhisar", "Hüyük", "Altınekin", "Hadim", "Güneysınır", "Emirgazi", "Tuzlukçu", "Derebucak", "Akören", "Taşkent", "Çeltik", "Derbent", "Yalıhüyük", "Ahırlı", "Halkapınar"],
  "Kütahya": ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet", "Altıntaş", "Domaniç", "Hisarcık", "Aslanapa", "Çavdarhisar", "Şaphane", "Pazarlar", "Dumlupınar"],
  "Malatya": ["Battalgazi", "Yeşilyurt", "Doğanşehir", "Darende", "Akçadağ", "Hekimhan", "Pütürge", "Yazıhan", "Arapgir", "Kuluncak", "Arguvan", "Kale", "Doğanyol"],
  "Manisa": ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Salihli", "Soma", "Alaşehir", "Saruhanlı", "Kula", "Demirci", "Kırkağaç", "Sarıgöl", "Gördes", "Selendi", "Ahmetli", "Gölmarmara", "Köprübaşı"],
  "Kahramanmaraş": ["Onikişubat", "Dulkadiroğlu", "Elbistan", "Afşin", "Pazarcık", "Göksun", "Türkoğlu", "Çağlayancerit", "Andırın", "Ekinözü", "Nurhak"],
  "Mardin": ["Artuklu", "Kızıltepe", "Midyat", "Nusaybin", "Derik", "Mazıdağı", "Dargeçit", "Savur", "Yeşilli", "Ömerli"],
  "Muğla": ["Bodrum", "Fethiye", "Milas", "Menteşe", "Marmaris", "Seydikemer", "Dalaman", "Yatağan", "Ortaca", "Datça", "Ula", "Köyceğiz", "Kavaklıdere"],
  "Muş": ["Merkez", "Bulanık", "Malazgirt", "Hasköy", "Varto", "Korkut"],
  "Nevşehir": ["Merkez", "Ürgüp", "Avanos", "Gülşehir", "Derinkuyu", "Kozaklı", "Acıgöl", "Hacıbektaş"],
  "Niğde": ["Merkez", "Bor", "Çiftlik", "Ulukışla", "Altunhisar", "Çamardı"],
  "Ordu": ["Altınordu", "Ünye", "Fatsa", "Gölköy", "Perşembe", "Kumru", "Korgan", "Akkuş", "Aybastı", "İkizce", "Ulubey", "Mesudiye", "Gürgentepe", "Çamaş", "Çatalpınar", "Çaybaşı", "Gülyalı", "Kabataş", "Kabadüz"],
  "Rize": ["Merkez", "Çayeli", "Ardeşen", "Pazar", "Kaçkar", "Fındıklı", "Güneysu", "Kalkandere", "İyidere", "Derepazarı", "Çamlıhemşin", "İkizdere", "Hemşin"],
  "Sakarya": ["Adapazarı", "Serdivan", "Erenler", "Hendek", "Akyazı", "Karasu", "Geyve", "Arifiye", "Sapanca", "Pamukova", "Kocaali", "Ferizli", "Kaynarca", "Söğütlü", "Taraklı", "Karapürçek"],
  "Samsun": ["İlkadım", "Atakum", "Canik", "Bafra", "Çarşamba", "Vezirköprü", "Terme", "Tekkeköy", "Havza", "Alaçam", "19 Mayis", "Salıpazarı", "Ayvacık", "Kavak", "Asarcık", "Yakakent", "Ladik"],
  "Siirt": ["Merkez", "Kurtalan", "Pervari", "Baykan", "Eruh", "Şirvan", "Tillo"],
  "Sinop": ["Merkez", "Boyabat", "Gerze", "Ayancık", "Durağan", "Türkeli", "Erfelek", "Dikmen", "Saraydüzü"],
  "Sivas": ["Merkez", "Şarkışla", "Yıldızeli", "Suşehri", "Zara", "Gemerek", "Kangal", "Divriği", "Gürün", "İmranlı", "Gölova", "Haçik", "Altınyayla", "Koyulhisar", "Ulaş", "Doğanşar"],
  "Tekirdağ": ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Kapaklı", "Ergene", "Şarköy", "Hayrabolu", "Malkara", "Saray", "Muratlı", "Marmaraereğlisi"],
  "Tokat": ["Merkez", "Erbaa", "Turhal", "Niksar", "Zile", "Reşadiye", "Almus", "Pazar", "Başçiftlik", "Yeşilyurt", "Artova", "Sulusaray"],
  "Trabzon": ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Sürmene", "Arsin", "Vakfıkebir", "Maçka", "Beşikdüzü", "Çarşıbaşı", "Tonya", "Düzköy", "Şalpazarı", "Çaykara", "Hayrat", "Dernekpazarı", "Köprübaşı"],
  "Tunceli": ["Merkez", "Pertek", "Mazgirt", "Çemişgezek", "Hozat", "Ovacık", "Pülümür", "Nazımiye"],
  "Şanlıurfa": ["Eyyübiye", "Haliliye", "Karaköprü", "Siverek", "Viranşehir", "Suruç", "Birecik", "Ceylanpınar", "Akçakale", "Harran", "Bozova", "Hilvan", "Halfeti"],
  "Uşak": ["Merkez", "Banaz", "Eşme", "Sivaslı", "Ulubey", "Karahallı"],
  "Van": ["İpekyolu", "Tuşba", "Edremit", "Erciş", "Özalp", "Çaldıran", "Muradiye", "Başkale", "Gürpınar", "Gevaş", "Çatak", "Bahçesaray", "Saray"],
  "Yozgat": ["Merkez", "Sorgun", "Akdağmadeni", "Yerköy", "Boğazlıyan", "Sarıkaya", "Çekerek", "Şefaatli", "Saraykent", "Çayıralan", "Kadışehri", "Aydıncık", "Yenifakılı", "Chandır"],
  "Zonguldak": ["Ereğli", "Merkez", "Çaycuma", "Devrek", "Kozlu", "Kilimli", "Alaplı", "Gökçebey"],
  "Aksaray": ["Merkez", "Ortaköy", "Eskil", "Gülağaç", "Güzelyurt", "Sultanhanı", "Ağaçören", "Sarıyahşi"],
  "Bayburt": ["Merkez", "Demirözü", "Aydıntepe"],
  "Karaman": ["Merkez", "Ermenek", "Sarıveliler", "Kazımkarabekir", "Başyayla", "Ayrancı"],
  "Kırıkkale": ["Merkez", "Yahşihan", "Keskin", "Delice", "Sulakyurt", "Bahşılı", "Balışeyh", "Karakeçili", "Çelebi"],
  "Batman": ["Merkez", "Kozluk", "Sason", "Beşiri", "Gercüş", "Hasankeyf"],
  "Şırnak": ["Merkez", "Cizre", "Silopi", "İdil", "Uludere", "Beytüşşebap", "Güçlükonak"],
  "Bartın": ["Merkez", "Amasra", "Ulus", "Kurucaşile"],
  "Ardahan": ["Merkez", "Göle", "Çıldır", "Hanak", "Posof", "Damal"],
  "Iğdır": ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"],
  "Yalva": ["Merkez", "Çiftlikköy", "Çınarcık", "Altınova", "Termal", "Armutlu"], // Yalova
  "Yalova": ["Merkez", "Çiftlikköy", "Çınarcık", "Altınova", "Termal", "Armutlu"],
  "Karabük": ["Merkez", "Safranbolu", "Yenice", "Eskipazar", "Eflani", "Ovacık"],
  "Kilis": ["Merkez", "Musabeyli", "Elbeyli", "Polateli"],
  "Osmaniye": ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Toprakkale", "Sumbas", "Hasanbeyli"],
  "Düzce": ["Merkez", "Akçakocan", "Akçakoca", "Gölyaka", "Çilimli", "Gümüşova", "Kaynaşlı", "Yığılca", "Cumayeri"]
};
