/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KulupRouteImport } from './routes/kulup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as PaymentCheckoutRouteImport } from './routes/payment/checkout'
import { Route as ProductRouteImport } from './routes/product.'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as SiparisIdRouteImport } from './routes/siparis.$id'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders.'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders.$id'
import { Route as AdminProductsEditRouteImport } from './routes/admin/products..edit'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products.new'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KulupRoute = KulupRouteImport.update({
  id: '/kulup',
  path: '/kulup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCheckoutRoute = PaymentCheckoutRouteImport.update({
  id: '/payment/checkout',
  path: '/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparisIdRoute = SiparisIdRouteImport.update({
  id: '/siparis/$id',
  path: '/siparis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsEditRoute = AdminProductsEditRouteImport.update({
  id: '/admin/products/edit',
  path: '/admin/products/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/admin/products/$id/edit',
  path: '/admin/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/iletisim': typeof IletisimRoute
  '/kulup': typeof KulupRoute
  '/shop': typeof ShopRoute
  '/product/': typeof ProductRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/payment/checkout': typeof PaymentCheckoutRoute
  '/product/$slug': typeof ProductSlugRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/': typeof AdminOrdersRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/edit': typeof AdminProductsEditRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/iletisim': typeof IletisimRoute
  '/kulup': typeof KulupRoute
  '/shop': typeof ShopRoute
  '/product': typeof ProductRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/payment/checkout': typeof PaymentCheckoutRoute
  '/product/$slug': typeof ProductSlugRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/edit': typeof AdminProductsEditRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/iletisim': typeof IletisimRoute
  '/kulup': typeof KulupRoute
  '/shop': typeof ShopRoute
  '/product/': typeof ProductRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/payment/checkout': typeof PaymentCheckoutRoute
  '/product/$slug': typeof ProductSlugRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/': typeof AdminOrdersRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/edit': typeof AdminProductsEditRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/iletisim'
    | '/kulup'
    | '/shop'
    | '/product/'
    | '/admin/dashboard'
    | '/payment/checkout'
    | '/product/$slug'
    | '/siparis/$id'
    | '/admin/'
    | '/admin/orders/'
    | '/admin/orders/$id'
    | '/admin/products/edit'
    | '/admin/products/new'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/iletisim'
    | '/kulup'
    | '/shop'
    | '/product'
    | '/admin/dashboard'
    | '/payment/checkout'
    | '/product/$slug'
    | '/siparis/$id'
    | '/admin'
    | '/admin/orders'
    | '/admin/orders/$id'
    | '/admin/products/edit'
    | '/admin/products/new'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/iletisim'
    | '/kulup'
    | '/shop'
    | '/product/'
    | '/admin/dashboard'
    | '/payment/checkout'
    | '/product/$slug'
    | '/siparis/$id'
    | '/admin/'
    | '/admin/orders/'
    | '/admin/orders/$id'
    | '/admin/products/edit'
    | '/admin/products/new'
    | '/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  IletisimRoute: typeof IletisimRoute
  KulupRoute: typeof KulupRoute
  ShopRoute: typeof ShopRoute
  ProductRoute: typeof ProductRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  PaymentCheckoutRoute: typeof PaymentCheckoutRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SiparisIdRoute: typeof SiparisIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsEditRoute: typeof AdminProductsEditRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kulup': {
      id: '/kulup'
      path: '/kulup'
      fullPath: '/kulup'
      preLoaderRoute: typeof KulupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/checkout': {
      id: '/payment/checkout'
      path: '/payment/checkout'
      fullPath: '/payment/checkout'
      preLoaderRoute: typeof PaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparis/$id': {
      id: '/siparis/$id'
      path: '/siparis/$id'
      fullPath: '/siparis/$id'
      preLoaderRoute: typeof SiparisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/edit': {
      id: '/admin/products/edit'
      path: '/admin/products/edit'
      fullPath: '/admin/products/edit'
      preLoaderRoute: typeof AdminProductsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/admin/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  IletisimRoute: IletisimRoute,
  KulupRoute: KulupRoute,
  ShopRoute: ShopRoute,
  ProductRoute: ProductRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  PaymentCheckoutRoute: PaymentCheckoutRoute,
  ProductSlugRoute: ProductSlugRoute,
  SiparisIdRoute: SiparisIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsEditRoute: AdminProductsEditRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
